all: GNU-amd64-Linux/_SIPSL

GNU-amd64-Linux/_SIPSL:  GNU-amd64-Linux/SEAMFAIL.o GNU-amd64-Linux/test.o GNU-amd64-Linux/CALL_OSET.o GNU-amd64-Linux/MESSAGE.o GNU-amd64-Linux/VALO.o GNU-amd64-Linux/DOA.o GNU-amd64-Linux/ENGINE.o GNU-amd64-Linux/SPIN.o GNU-amd64-Linux/SIPUTIL.o GNU-amd64-Linux/CS_HEADERS.o GNU-amd64-Linux/SIPENGINE.o GNU-amd64-Linux/TRNSPRT.o GNU-amd64-Linux/SUDP.o GNU-amd64-Linux/ACTION.o GNU-amd64-Linux/TRNSCT_SM.o GNU-amd64-Linux/DAO.o GNU-amd64-Linux/SL_CC.o GNU-amd64-Linux/COMAP.o GNU-amd64-Linux/ALARM.o GNU-amd64-Linux/ALO.o
        g++ -O -s -m64      -o GNU-amd64-Linux/_SIPSL GNU-amd64-Linux/SEAMFAIL.o GNU-amd64-Linux/test.o GNU-amd64-Linux/CALL_OSET.o GNU-amd64-Linux/MESSAGE.o GNU-amd64-Linux/VALO.o GNU-amd64-Linux/DOA.o GNU-amd64-Linux/ENGINE.o GNU-amd64-Linux/SPIN.o GNU-amd64-Linux/SIPUTIL.o GNU-amd64-Linux/CS_HEADERS.o GNU-amd64-Linux/SIPENGINE.o GNU-amd64-Linux/TRNSPRT.o GNU-amd64-Linux/SUDP.o GNU-amd64-Linux/ACTION.o GNU-amd64-Linux/TRNSCT_SM.o GNU-amd64-Linux/DAO.o GNU-amd64-Linux/SL_CC.o GNU-amd64-Linux/COMAP.o GNU-amd64-Linux/ALARM.o GNU-amd64-Linux/ALO.o -lpthread

GNU-amd64-Linux/SIPUTIL.o : src/SIPUTIL.cpp
        g++ -O -s -m64  -c   -o GNU-amd64-Linux/SIPUTIL.o src/SIPUTIL.cpp -I hdr  -std=gnu++0x

GNU-amd64-Linux/SEAMFAIL.o : src/SEAMFAIL.cpp
        g++ -O -s -m64   -c   -o GNU-amd64-Linux/SEAMFAIL.o src/SEAMFAIL.cpp -I hdr  -std=gnu++0x


GNU-amd64-Linux/test.o : src/test.cpp
        g++ -O -s -m64   -c   -o GNU-amd64-Linux/test.o src/test.cpp -I hdr  -std=gnu++0x

GNU-amd64-Linux/CALL_OSET.o : src/CALL_OSET.cpp
        g++ -O -s -m64   -c   -o GNU-amd64-Linux/CALL_OSET.o src/CALL_OSET.cpp -I hdr  -std=gnu++0x

GNU-amd64-Linux/MESSAGE.o : src/MESSAGE.cpp
        g++ -O -s -m64   -c   -o GNU-amd64-Linux/MESSAGE.o src/MESSAGE.cpp -I hdr  -std=gnu++0x

GNU-amd64-Linux/VALO.o : src/VALO.cpp
        g++ -O -s -m64   -c   -o GNU-amd64-Linux/VALO.o src/VALO.cpp -I hdr  -std=gnu++0x

GNU-amd64-Linux/DOA.o : src/DOA.cpp
        g++ -O -s -m64   -c   -o GNU-amd64-Linux/DOA.o src/DOA.cpp -I hdr  -std=gnu++0x

GNU-amd64-Linux/ENGINE.o : src/ENGINE.cpp
        g++ -O -s -m64   -c   -o GNU-amd64-Linux/ENGINE.o src/ENGINE.cpp -I hdr  -std=gnu++0x

GNU-amd64-Linux/SPIN.o : src/SPIN.cpp
        g++ -O -s -m64   -c   -o GNU-amd64-Linux/SPIN.o src/SPIN.cpp -I hdr  -std=gnu++0x

GNU-amd64-Linux/GNU-amd64-Linux/SIPUTIL.o : src/SIPUTIL.cpp
        g++ -O -s -m64   -c   -o GNU-amd64-Linux/SIPUTIL.o src/SIPUTIL.cpp -I hdr  -std=gnu++0x

GNU-amd64-Linux/CS_HEADERS.o : src/CS_HEADERS.cpp
        g++ -O -s -m64   -c   -o GNU-amd64-Linux/CS_HEADERS.o src/CS_HEADERS.cpp -I hdr  -std=gnu++0x

GNU-amd64-Linux/SIPENGINE.o : src/SIPENGINE.cpp
        g++ -O -s -m64   -c   -o GNU-amd64-Linux/SIPENGINE.o src/SIPENGINE.cpp -I hdr  -std=gnu++0x

GNU-amd64-Linux/TRNSPRT.o : src/TRNSPRT.cpp
        g++ -O -s -m64   -c   -o GNU-amd64-Linux/TRNSPRT.o src/TRNSPRT.cpp -I hdr  -std=gnu++0x

GNU-amd64-Linux/ACTION.o : src/ACTION.cpp
        g++ -O -s -m64   -c   -o GNU-amd64-Linux/ACTION.o src/ACTION.cpp -I hdr  -std=gnu++0x

GNU-amd64-Linux/TRNSCT_SM.o : src/TRNSCT_SM.cpp
        g++ -O -s -m64   -c   -o GNU-amd64-Linux/TRNSCT_SM.o src/TRNSCT_SM.cpp -I hdr  -std=gnu++0x

GNU-amd64-Linux/DAO.o : src/DAO.cpp
        g++ -O -s -m64   -c   -o GNU-amd64-Linux/DAO.o src/DAO.cpp -I hdr  -std=gnu++0x

GNU-amd64-Linux/SL_CC.o : src/SL_CC.cpp
        g++ -O -s -m64   -c   -o GNU-amd64-Linux/SL_CC.o src/SL_CC.cpp -I hdr  -std=gnu++0x

GNU-amd64-Linux/COMAP.o : src/COMAP.cpp
        g++ -O -s -m64   -c   -o GNU-amd64-Linux/COMAP.o src/COMAP.cpp -I hdr  -std=gnu++0x

GNU-amd64-Linux/ALARM.o : src/ALARM.cpp
        g++ -O -s -m64   -c   -o GNU-amd64-Linux/ALARM.o src/ALARM.cpp -I hdr  -std=gnu++0x

GNU-amd64-Linux/ALO.o : src/ALO.cpp
        g++ -O -s -m64   -c   -o GNU-amd64-Linux/ALO.o src/ALO.cpp -I hdr  -std=gnu++0x

GNU-amd64-Linux/SUDP.o : src/SUDP.cpp
        g++ -O -s -m64   -c   -o GNU-amd64-Linux/SUDP.o src/SUDP.cpp -I hdr  -std=gnu++0x
